#+TITLE: Making a lame scale with a RaspberryPI and a force-sensitive resistor
#+AUTHOR: Andrew Caird
#+EMAIL: acaird@gmail.com

* Motivation

  I wanted to make a little scale for my jar of coffee beans so I can plot
  the weight of it over time and note when it is low so I can buy fresh
  beans.

* The Script

  This script was taken from [[https://learn.adafruit.com/reading-a-analog-in-and-controlling-audio-volume-with-the-raspberry-pi/connecting-the-cobbler-to-a-mcp3008][learn.adafruit]]
  and is also available at [[https://gist.github.com/ladyada/3151375#file-adafruit_mcp3008-py]]
  and modified a little to work with the FSR and not the potentiometer in their script.

* The Wiring

  The breadboard layout looks like this:

  #+ATTR_HTML: :width 50%
   [[file:images/lamescale_bb.pdf][file:images/lamescale_bb.png]]

  (Drawn with the totally fun [[http://fritzing.org/home/][Fritzing]] and the [[https://github.com/adafruit/Fritzing-Library][Adafruit Fritzing
  Library]])

  To load the files in the ~fritzing-files~ directory into Fritzing
  directly you can open the ~.fz~ file, although you'll be prompted to
  convert it to a ~.fzz~ file, or you can make the ~.fzz~ file
  yourself from the files in that directory by going into it and
  typing:
  #+BEGIN_EXAMPLE
     zip ../lamescale.fzz *
  #+END_EXAMPLE
  then opening the resulting ~lamescale.fzz~ file in Fritzing.  I keep
  the files un-zipped in the git repository for version tracking, so
  you can get whatever version you want from there.

* The License

  I don't know what the license on Adafruit's script is, but mine follows that.  If there isn't a license
  on their script, mine is [[http://creativecommons.org/licenses/by-sa/4.0/][CC By-SA]].
